# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

## THIS IS THE VAGRANTFILE FOR "mhc-cs/cs_221" Ubuntu 20.04 with Xfce GUI
## updated 2022-09-16 with local box file

ENV['VAGRANT_INSTALL_LOCAL_PLUGINS'] = "true"

#  myhostname = "cs221"

  # create a vm with username and timestamp appended (to avoid duplicate names)

  require 'date'
  username = ENV['USERNAME'] || ENV['USER']
  myDate = DateTime.now.strftime('%Y-%m-%d-%H.%M.%S')
  myhostname = "#{username.gsub(/\s/, "-")}-linux-vm-#{myDate}"

Vagrant.configure("2") do |config|

#  config.vm.box = "/Users/Shared/boxes/virtualbox.box"
  config.vm.box = "mhc-cs/Ubuntu-20-04-Xfce"
  config.vm.hostname = "#{myhostname}"
  config.vagrant.plugins = ["vagrant-timezone", "vagrant-vbguest"]
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-timezone") ## sync the guest clock to host if timezone plugin is installed
    config.timezone.value = :host
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.name = "#{myhostname}"
    v.gui = true ## controls GUI auto start
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
           # Set the video memory to 64Mb:
    v.customize ["modifyvm", :id, "--vram", "64"]
           # enable shared clipboard
    v.customize  ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
  end

  config.trigger.after :up  do |updatePkgs|
  end

  config.vm.synced_folder "./shared", "/home/vagrant/Desktop/shared", create: true, type: "virtualbox", owner: "vagrant", group: "vagrant", mount_options: ["dmode=770", "fmode=770"]

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-17-jdk net-tools 
  SHELL
end
