# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

## THIS IS THE VAGRANTFILE FOR "mhc-cs/MHC221-ubuntu-xfce"

# create a vm with username and timestamp appended (to avoid duplicate names)

  require 'date'

  username = ENV['USERNAME'] || ENV['USER']
  myDate = DateTime.now.strftime('%Y-%m-%d-%H.%M.%S')
  myhostname = "#{username}-UbuntuXfce-vm-#{myDate}"

Vagrant.configure("2") do |config|

  config.vm.box = "mhc-cs/MHC221-ubuntu-xfce.box"
  config.vm.hostname = "#{myhostname}"
  config.vagrant.plugins = ["vagrant-timezone", "vagrant-vbguest"]

  if Vagrant.has_plugin?("vagrant-timezone") ## sync the guest clock to host if timezone plugin is installed
    config.timezone.value = :host
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.name = "#{myhostname}"
    v.gui = true
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.trigger.after :up  do |updatePkgs|
    updatePkgs.warn = "Checking for software updates"
    updatePkgs.run_remote = {inline: "apt-get --with-new-pkgs upgrade -y"}
  end

  config.vm.synced_folder "./shared", "/home/vagrant/Desktop/shared", create: true
  config.vm.provision :shell, inline: "chown -R vagrant:vagrant /home/vagrant/Desktop/shared/ && ln -sfn /home/vagrant/Desktop/shared/ /shared/ ; "

  ## this is probably what caused the shared folder to break
  # config.vm.provision :shell, inline: "mkdir -p /home/vagrant/Desktop && chown vagrant:vagrant /home/vagrant/Desktop /shared/ && ln -sfn /shared /home/vagrant/Desktop/ ;"

end
