# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

## THIS IS THE VAGRANTFILE FOR GENERIC 'my-linux-vm'

# install missing plugins without asking user permission
  ENV['VAGRANT_INSTALL_LOCAL_PLUGINS'] = "true"

# create a vm with username and timestamp appended (to avoid duplicate names)

  require 'date'
  username = ENV['USERNAME'] || ENV['USER']
  myDate = DateTime.now.strftime('%Y-%m-%d-%H.%M.%S')
  myhostname = "#{username.gsub(/\s/, "-")}-linux-vm-#{myDate}"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "#{myhostname}"
    if Vagrant.has_plugin?("vagrant-timezone") ## sync the guest clock to host if timezone plugin is installed
    config.timezone.value = :host
  end
  config.vm.provision :shell, path: "install-extras.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "#{myhostname}"
  end

  config.trigger.after :up  do |updatePkgs|
  	updatePkgs.warn = "Checking for software updates"
  	updatePkgs.run_remote = {inline: "apt-get --with-new-pkgs upgrade -y"}
  end

  config.vm.synced_folder "./shared", "/shared", create: true

end
